// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Math.proto

package com.gyzh.zain.rpc.gpf;

public final class MathServicex {
  private MathServicex() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 num1 = 1;</code>
     */
    boolean hasNum1();
    /**
     * <code>required int32 num1 = 1;</code>
     */
    int getNum1();

    /**
     * <code>required int32 num2 = 2;</code>
     */
    boolean hasNum2();
    /**
     * <code>required int32 num2 = 2;</code>
     */
    int getNum2();

    /**
     * <code>required string mname = 3;</code>
     */
    boolean hasMname();
    /**
     * <code>required string mname = 3;</code>
     */
    java.lang.String getMname();
    /**
     * <code>required string mname = 3;</code>
     */
    com.google.protobuf.ByteString
        getMnameBytes();
  }
  /**
   * Protobuf type {@code Req}
   */
  public static final class Req extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Req)
      ReqOrBuilder {
    // Use Req.newBuilder() to construct.
    private Req(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Req(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Req defaultInstance;
    public static Req getDefaultInstance() {
      return defaultInstance;
    }

    public Req getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              num1_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              num2_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              mname_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Req_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gyzh.zain.rpc.gpf.MathServicex.Req.class, com.gyzh.zain.rpc.gpf.MathServicex.Req.Builder.class);
    }

    public static com.google.protobuf.Parser<Req> PARSER =
        new com.google.protobuf.AbstractParser<Req>() {
      public Req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Req(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Req> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NUM1_FIELD_NUMBER = 1;
    private int num1_;
    /**
     * <code>required int32 num1 = 1;</code>
     */
    public boolean hasNum1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 num1 = 1;</code>
     */
    public int getNum1() {
      return num1_;
    }

    public static final int NUM2_FIELD_NUMBER = 2;
    private int num2_;
    /**
     * <code>required int32 num2 = 2;</code>
     */
    public boolean hasNum2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 num2 = 2;</code>
     */
    public int getNum2() {
      return num2_;
    }

    public static final int MNAME_FIELD_NUMBER = 3;
    private java.lang.Object mname_;
    /**
     * <code>required string mname = 3;</code>
     */
    public boolean hasMname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string mname = 3;</code>
     */
    public java.lang.String getMname() {
      java.lang.Object ref = mname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMnameBytes() {
      java.lang.Object ref = mname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      num1_ = 0;
      num2_ = 0;
      mname_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNum1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, num1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, num2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMnameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMnameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gyzh.zain.rpc.gpf.MathServicex.Req prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Req)
        com.gyzh.zain.rpc.gpf.MathServicex.ReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Req_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gyzh.zain.rpc.gpf.MathServicex.Req.class, com.gyzh.zain.rpc.gpf.MathServicex.Req.Builder.class);
      }

      // Construct using com.gyzh.zain.rpc.gpf.MathServicex.Req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        num1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        num2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        mname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Req_descriptor;
      }

      public com.gyzh.zain.rpc.gpf.MathServicex.Req getDefaultInstanceForType() {
        return com.gyzh.zain.rpc.gpf.MathServicex.Req.getDefaultInstance();
      }

      public com.gyzh.zain.rpc.gpf.MathServicex.Req build() {
        com.gyzh.zain.rpc.gpf.MathServicex.Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gyzh.zain.rpc.gpf.MathServicex.Req buildPartial() {
        com.gyzh.zain.rpc.gpf.MathServicex.Req result = new com.gyzh.zain.rpc.gpf.MathServicex.Req(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.num1_ = num1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.num2_ = num2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mname_ = mname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gyzh.zain.rpc.gpf.MathServicex.Req) {
          return mergeFrom((com.gyzh.zain.rpc.gpf.MathServicex.Req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gyzh.zain.rpc.gpf.MathServicex.Req other) {
        if (other == com.gyzh.zain.rpc.gpf.MathServicex.Req.getDefaultInstance()) return this;
        if (other.hasNum1()) {
          setNum1(other.getNum1());
        }
        if (other.hasNum2()) {
          setNum2(other.getNum2());
        }
        if (other.hasMname()) {
          bitField0_ |= 0x00000004;
          mname_ = other.mname_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNum1()) {
          
          return false;
        }
        if (!hasNum2()) {
          
          return false;
        }
        if (!hasMname()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gyzh.zain.rpc.gpf.MathServicex.Req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gyzh.zain.rpc.gpf.MathServicex.Req) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int num1_ ;
      /**
       * <code>required int32 num1 = 1;</code>
       */
      public boolean hasNum1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 num1 = 1;</code>
       */
      public int getNum1() {
        return num1_;
      }
      /**
       * <code>required int32 num1 = 1;</code>
       */
      public Builder setNum1(int value) {
        bitField0_ |= 0x00000001;
        num1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num1 = 1;</code>
       */
      public Builder clearNum1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num1_ = 0;
        onChanged();
        return this;
      }

      private int num2_ ;
      /**
       * <code>required int32 num2 = 2;</code>
       */
      public boolean hasNum2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 num2 = 2;</code>
       */
      public int getNum2() {
        return num2_;
      }
      /**
       * <code>required int32 num2 = 2;</code>
       */
      public Builder setNum2(int value) {
        bitField0_ |= 0x00000002;
        num2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num2 = 2;</code>
       */
      public Builder clearNum2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num2_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mname_ = "";
      /**
       * <code>required string mname = 3;</code>
       */
      public boolean hasMname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string mname = 3;</code>
       */
      public java.lang.String getMname() {
        java.lang.Object ref = mname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMnameBytes() {
        java.lang.Object ref = mname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mname = 3;</code>
       */
      public Builder setMname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mname = 3;</code>
       */
      public Builder clearMname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mname_ = getDefaultInstance().getMname();
        onChanged();
        return this;
      }
      /**
       * <code>required string mname = 3;</code>
       */
      public Builder setMnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mname_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Req)
    }

    static {
      defaultInstance = new Req(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Req)
  }

  public interface ResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Res)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code Res}
   */
  public static final class Res extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Res)
      ResOrBuilder {
    // Use Res.newBuilder() to construct.
    private Res(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Res(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Res defaultInstance;
    public static Res getDefaultInstance() {
      return defaultInstance;
    }

    public Res getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Res(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Res_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Res_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gyzh.zain.rpc.gpf.MathServicex.Res.class, com.gyzh.zain.rpc.gpf.MathServicex.Res.Builder.class);
    }

    public static com.google.protobuf.Parser<Res> PARSER =
        new com.google.protobuf.AbstractParser<Res>() {
      public Res parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Res(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Res> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gyzh.zain.rpc.gpf.MathServicex.Res parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gyzh.zain.rpc.gpf.MathServicex.Res prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Res}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Res)
        com.gyzh.zain.rpc.gpf.MathServicex.ResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Res_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Res_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gyzh.zain.rpc.gpf.MathServicex.Res.class, com.gyzh.zain.rpc.gpf.MathServicex.Res.Builder.class);
      }

      // Construct using com.gyzh.zain.rpc.gpf.MathServicex.Res.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gyzh.zain.rpc.gpf.MathServicex.internal_static_Res_descriptor;
      }

      public com.gyzh.zain.rpc.gpf.MathServicex.Res getDefaultInstanceForType() {
        return com.gyzh.zain.rpc.gpf.MathServicex.Res.getDefaultInstance();
      }

      public com.gyzh.zain.rpc.gpf.MathServicex.Res build() {
        com.gyzh.zain.rpc.gpf.MathServicex.Res result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gyzh.zain.rpc.gpf.MathServicex.Res buildPartial() {
        com.gyzh.zain.rpc.gpf.MathServicex.Res result = new com.gyzh.zain.rpc.gpf.MathServicex.Res(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gyzh.zain.rpc.gpf.MathServicex.Res) {
          return mergeFrom((com.gyzh.zain.rpc.gpf.MathServicex.Res)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gyzh.zain.rpc.gpf.MathServicex.Res other) {
        if (other == com.gyzh.zain.rpc.gpf.MathServicex.Res.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gyzh.zain.rpc.gpf.MathServicex.Res parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gyzh.zain.rpc.gpf.MathServicex.Res) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Res)
    }

    static {
      defaultInstance = new Res(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Res)
  }

  /**
   * Protobuf service {@code MathService}
   */
  public static abstract class MathService
      implements com.google.protobuf.Service {
    protected MathService() {}

    public interface Interface {
      /**
       * <code>rpc add(.Req) returns (.Res);</code>
       */
      public abstract void add(
          com.google.protobuf.RpcController controller,
          com.gyzh.zain.rpc.gpf.MathServicex.Req request,
          com.google.protobuf.RpcCallback<com.gyzh.zain.rpc.gpf.MathServicex.Res> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new MathService() {
        @java.lang.Override
        public  void add(
            com.google.protobuf.RpcController controller,
            com.gyzh.zain.rpc.gpf.MathServicex.Req request,
            com.google.protobuf.RpcCallback<com.gyzh.zain.rpc.gpf.MathServicex.Res> done) {
          impl.add(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.add(controller, (com.gyzh.zain.rpc.gpf.MathServicex.Req)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.gyzh.zain.rpc.gpf.MathServicex.Req.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.gyzh.zain.rpc.gpf.MathServicex.Res.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc add(.Req) returns (.Res);</code>
     */
    public abstract void add(
        com.google.protobuf.RpcController controller,
        com.gyzh.zain.rpc.gpf.MathServicex.Req request,
        com.google.protobuf.RpcCallback<com.gyzh.zain.rpc.gpf.MathServicex.Res> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.gyzh.zain.rpc.gpf.MathServicex.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.add(controller, (com.gyzh.zain.rpc.gpf.MathServicex.Req)request,
            com.google.protobuf.RpcUtil.<com.gyzh.zain.rpc.gpf.MathServicex.Res>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.gyzh.zain.rpc.gpf.MathServicex.Req.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.gyzh.zain.rpc.gpf.MathServicex.Res.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.gyzh.zain.rpc.gpf.MathServicex.MathService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void add(
          com.google.protobuf.RpcController controller,
          com.gyzh.zain.rpc.gpf.MathServicex.Req request,
          com.google.protobuf.RpcCallback<com.gyzh.zain.rpc.gpf.MathServicex.Res> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.gyzh.zain.rpc.gpf.MathServicex.Res.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.gyzh.zain.rpc.gpf.MathServicex.Res.class,
            com.gyzh.zain.rpc.gpf.MathServicex.Res.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.gyzh.zain.rpc.gpf.MathServicex.Res add(
          com.google.protobuf.RpcController controller,
          com.gyzh.zain.rpc.gpf.MathServicex.Req request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.gyzh.zain.rpc.gpf.MathServicex.Res add(
          com.google.protobuf.RpcController controller,
          com.gyzh.zain.rpc.gpf.MathServicex.Req request)
          throws com.google.protobuf.ServiceException {
        return (com.gyzh.zain.rpc.gpf.MathServicex.Res) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.gyzh.zain.rpc.gpf.MathServicex.Res.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:MathService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Req_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Res_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Res_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nMath.proto\"0\n\003Req\022\014\n\004num1\030\001 \002(\005\022\014\n\004num" +
      "2\030\002 \002(\005\022\r\n\005mname\030\003 \002(\t\"\025\n\003Res\022\016\n\006result\030" +
      "\001 \002(\0052 \n\013MathService\022\021\n\003add\022\004.Req\032\004.ResB" +
      "(\n\025com.gyzh.zain.rpc.gpfB\014MathServicex\210\001" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Req_descriptor,
        new java.lang.String[] { "Num1", "Num2", "Mname", });
    internal_static_Res_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Res_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Res_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
